In [1]:
import pandas as pd

In [2]:
pd.read_csv('vehpub.csv').head(10)

,HOUSEID,VEHID,VEHYEAR,VEHAGE,MAKE,MODEL,FUELTYPE,VEHTYPE,WHOMAIN,OD_READ,...,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN,GSYRGAL,GSTOTCST,FEGEMPG,FEGEMPGA,GSCOST,FEGEMPGF
0,30000007,1,2007,10,49,49032,1,1,3,69000,...,750,20,750,300,487.064221,1126.457778,30,-9,2.312750,1
1,30000007,2,2004,13,49,49442,1,2,-8,164000,...,750,20,750,300,250.899523,580.267873,19,-9,2.312750,1
2,30000007,3,1998,19,19,19014,1,1,1,120000,...,750,20,750,300,444.462475,1027.930589,18,-9,2.312750,1
3,30000007,4,1997,20,19,19021,1,1,2,-88,...,750,20,750,300,40.329575,93.272224,18,-9,2.312750,1
4,30000007,5,1993,24,20,20481,1,4,2,300000,...,750,20,750,300,888.404197,2054.656806,14,-9,2.312750,1
5,30000008,1,2014,3,20,20028,1,1,97,-88,...,150,5,300,300,210.331757,476.716926,29,-9,2.266500,1
6,30000008,2,2010,7,20,20024,1,3,2,-88,...,150,5,300,300,677.137458,1534.732049,19,-9,2.266500,1
7,30000008,3,2008,9,20,20039,1,1,97,-88,...,150,5,300,300,226.612423,513.617057,27,-9,2.266500,1
8,30000008,4,2004,13,20,20481,1,4,1,128000,...,150,5,300,300,651.859696,1477.440002,15,-9,2.266500,1
9,30000012,1,2011,6,58,58037,1,1,1,70115,...,5000,60,17000,7000,219.853193,542.011404,21,-9,2.465333,1